### ISSUE TITLE
Mapping product review to variety

### ISSUE THREAD

**Issue by jppgks** [alexcaza/firstbloom-data#1]
Hi, thanks for sharing this data! I'm trying to map a product review back to the variety that was reviewed, but it seems like that information is not shared? There's `product_release_id` for each review but there seems to be a one-to-many mapping between "product release" and "variety". Any way to trace a review back to a single variety?

**Comment by alexcaza** [comment]
If you look at the `product_release_varieties` [CSV](https://github.com/alexcaza/firstbloom-data/blob/main/product_release_varieties_202312201400.csv), you should be able to find what you're looking for!

Packaged coffees could have many varieties, and packaged coffees had many releases (say a blend went away, then came back but the varieties of that blend changed), so we needed a way to track those changes over time.

To build reviews for a single variety it would be something like:

```sql
SELECT * FROM
product_release_varieties prv
JOIN varieties v on prv.variety_id = v.id
JOIN first_bloom_user_product_reviews fbupr on fbupr.product_release_id = prv.product_release_id
WHERE v.id = {the_variety_you_want}
```

I'm pulling the SQL out of my memory, so it might not work copy/paste, but it should get you in the right direction 😄
